### ISSUE TITLE
pip install -e . will have a error

### ISSUE THREAD

**Issue by Cao-Zonghan** [ZJU-FAST-Lab/Radar-Diffusion#3]
If I want to install patchwork++ by using 'pip install -e .'  It will have a error :
ERROR: file:///home/czh/code/Radar-Diffusion/Coloradar_pre_processing/patchwork-plusplus does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
We should used :make pyinstall

**Comment by RoboticsZhang** [comment]
Thanks. I've made the corresponding changes in README.
