### ISSUE TITLE
"This repository is over its data quota", 请问有其他方式下载checkpoint的内容吗？

### ISSUE THREAD

**Issue by Aracano** [ZJU-FAST-Lab/Radar-Diffusion#4]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/ZJU-FAST-Lab/Radar-Diffusion.git/info/lfs'

无法下载git lfs的内容，请问有其他方式下载checkpoint里的内容吗？

**Comment by RoboticsZhang** [comment]
I‘ve uploaded the checkpoints in the NAS of our LAB. See "News" to download them.
