### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by ymx21** [ZJU-FAST-Lab/Radar-Diffusion#5]
The onedrive keeps interrupting halfway through the download, and the ZJU's netdisk (alternate link) doesn't work either!

**Comment by RoboticsZhang** [comment]
Hello, the onedrive link is indeed very unstable. I made a lot of efforts to download the dataset, so I suggest using the alternative link I provided. 

I've just checked the alternate link in a public network environment (not in our group's local network) and I can successfully download the dataset.  You can try to copy the download link to Thunder or  IDM download manager.

![{DE132533-6A6D-469f-9510-CA1D81F49C67}](https://github.com/user-attachments/assets/4edca12c-49a9-43b4-aa70-5978922a5297)

**Comment by ymx21** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ymx21** [comment]
非常感谢及时的回复，网络已经恢复！
